### ISSUE TITLE
Slow restructuring TreeChart with a large number of photos

### ISSUE THREAD

**Issue by Serg-Norseman** [Serg-Norseman/GEDKeeper#116]
Slow restructuring TreeChart with a large number of photos.
Especially in the case of portraits of large files photos.
It is necessary to develop caching mechanism of portraits (lightweight bitmaps, userdata folder, fast access).

**Comment by ruslangaripov** [comment]
@Serg-Norseman, since you added me as "assigned" to this ticket, and mark the latter with "help wanted", I have to ask you for more details on the issue.

The main issue is low performance of a 'Tree chart' when it comes to render some large number of bitmaps.

As your commits bba0ca6 and 53deee5 show, the cause to this issue is frequent bitmap scaling and **optional** file extracting from an archive made by class `BaseContext`. Am I right?

**Comment by Serg-Norseman** [comment]
The problem only showed up at Igor. He's got a lot of photos-portraits in the tree. When he first opens the tree, or in any rearrangements of the tree - there is a pause. Based on the structure of the implementation, I think that the problem is probably only in the load portraits. I doubt that the change in sizes plays a big role.

I will do simple pre-implementation. And then we will decide what is missing.

**Comment by ruslangaripov** [comment]
What kind of cache are you going to implement? In-memory one, or something 
else? In the commits I've mentioned before I saw an implementation based on 
the file-system only.

Yours truly,
Ruslan Garipov <ruslanngaripov at gmail dot com>.

**Comment by Serg-Norseman** [comment]
Now supports caching in-memory and disk together. However, there isn't another implementation of delete images from the cache, when changing a given portrait's region or portrait's picture.
