### ISSUE TITLE
GEDCOM Export writes empty HUSB/WIFE entries

### ISSUE THREAD

**Issue by fire-eggs** [Serg-Norseman/GEDKeeper#144]
When a family doesn't have spouse data, the GEDCOM export is writing empty records. Observed with GEDKeeper 2.8.1.0.

I.e. if there is no father data, export writes a "1 HUSB" line. Or a "1 WIFE" line if no mother data.

Export should write no HUSB/WIFE line when there is no data.

GEDCOM validators issue an error about the missing cross-reference id.

**Comment by Serg-Norseman** [comment]
Yes, I know about it. Everything somehow did not find time to fix this incompatibility - except for you about this reported only one user. Thank you!

**Comment by Serg-Norseman** [comment]
You did not have the desire to join forces in creating a genealogical program? I would be glad to see you as a participant in the GK project. Of course you have your own excellent library for reading / writing and you would not be interested in working with someone else's code for the same part. But those ideas that you have showed in the demos are very interesting and it would be cool to work together on a common theme.

Of course there are disadvantages, of late I am very disappointed with the main directions available for providing cross-platform desktop applications. I even think about leaving with ends in Java. Literally now I'm experimenting with porting the program. But this is still in doubt.

Last week I completed the draft porting of the GK project to the Eto framework. Now it is executed with a native interface on Windows and Linux. Probably on the Mac, but  for me there's no way to check. Unfortunately, there are a lot of problems, from which I'm ... tired.

So I sit and think ...

**Comment by fire-eggs** [comment]
Sergey -
>You did not have the desire to join forces in creating a genealogical
>program? I would be glad to see you as a participant in the GK project.

Actually, I'd like to take you up on that offer! I've been wondering if
some synergy was possible in Genealogy open source. I've been poking at
various C# open source projects: GedKeeper and Family Tree Analyzer (FTA)
are the two of the best/advanced projects I've found.

I like to be able to work on multiple, related projects - for variety and
inspiration. GK is more attractive to me than FTA because of the better
localization support, GEDCOM export, and more features. If you're open to
having me on
board, if there are ways I can help out, I'm happy to do so!

Let me know how you want to proceed with project access, tasks, directions,
coordination, etc. In the extreme short-term, I need to get caught up with
the latest in GK and get back up to speed. It would probably help my focus
if you had some specific small/medium goals or tasks I could work on for a
next release. On the other hand, I could poke around and come up with ideas
to talk about. Or on the gripping hand, throw me into the deep end with
your porting dilemma...

>I am very disappointed with ...  cross-platform desktop
Cross-platform has always been a challenge. It's not helping that Microsoft
seems to be dragging it's feet with Net.CORE. Did Winforms.Mono /
Xamarin.Forms not work out for some reason?

Its been a long time since I worked with Java/Swing - I think there are
better options now. I don't have any Mac experience or access. I have a
Linux box and Android Studio.

Eto is new to me.

>So I sit and think ...
Sometimes thinking with two brains is helpful :)

Sorry to be all over the place, this is kinda exciting!
Kevin

**Comment by Serg-Norseman** [comment]
#145

**Comment by Serg-Norseman** [comment]
Kevin,

I did not expect that my question would lead to such an unusual answer. Therefore, it will take me a while to formulate and record the basic thoughts about GK, ideas, plans, dreams and necessarily - current problems and weaknesses. Most likely, a few days.

In many ways, time is also needed because I do not want to dictate my will what and how to do to others. So I need to determine the directions, as I see them, and discuss together.

I wrote my message, because constantly looking for the solution of the main question - how to make a good work program for us, professionals and fans of genealogy, a reliable tool. Preserving advantages and eliminating flaws. And, I confess, I've lost my course recently.

Because it is necessary to find a solution that would ensure the stability of development on any basis, and as much as possible would isolate the development from the constant throwing of such companies as MS (constant shots from side to side, from one fashionable technology to another). But without giving up progressive techniques and methods.

I created a ticket/issue, which will be the best place for public discussion in the future.

**Comment by fire-eggs** [comment]
> it will take me a while to formulate and record the basic thoughts about
GK, >ideas, plans, dreams and necessarily - current problems and
weaknesses.
Definitely understood - collaboration does take a little more planning and
thinking ahead.

> I do not want to dictate my will
Just keep in mind that it is *your* project, and the work should at least
be in part to satisfy *your* goals. Not that there isn't room for more
ideas and directions. Of course, if the goals are a little uncertain right
now, this is a chance to get some help with directions :)

>I did not expect that my question would lead to such an unusual answer.
I hope it was a pleasant surprise ... I don't like to push myself too
aggressively onto other projects (I had some negative experience on the
receiving end in the past).

My thanks for the vote of confidence and the offer to join!
​
