### ISSUE TITLE
Install on WinXP does not show English and ...

### ISSUE THREAD

**Issue by Dreamer451** [Serg-Norseman/GEDKeeper#215]
On a clean install of Windows XP (32-bit) I ran the install for GEDKeeper 2.15. During the install, the English language was not displayed. Also, the following showed in the languages (2 square boxes):
![GEDKeeper2 - setup](https://user-images.githubusercontent.com/8588144/58027523-a9f80980-7acd-11e9-9e29-80f632a7d771.jpg)

**Comment by Serg-Norseman** [comment]
English according to the installer code - localization installed by default. Without choice. Do we really need a selection option?

**Comment by Dreamer451** [comment]
The installer itself does not need localization in my opinion. I just wanted to point out that one of the languages to install (Simplified Chinese) shows as “□□”. According to Google translate the characters used for this language are correct.

 

[insert puzzled expression here]

 

Kevin

**Comment by Serg-Norseman** [comment]
I think I said something wrong :)

English localization in accordance with the installer code - set by default to the user. No choice in the installer. Therefore, there is no visual option. But we can add it, because this situation may not be obvious to the user.

Perhaps I'll add it ...

With the Chinese localization will have to deal seriously :(

**Comment by Serg-Norseman** [comment]
Added mandatory non-switchable option for English. With the Chinese language is not yet clear

**Comment by Serg-Norseman** [comment]
No suitable information found, no solution found. The problem is postponed as outdated.
