### ISSUE TITLE
2.16 RC1 fails to execute

### ISSUE THREAD

**Issue by Dreamer451** [Serg-Norseman/GEDKeeper#222]
I extracted the portable files for version 2.16.0 RC1 to my app folder. I try to run the executable and nothing appears to happen. This is a Windows 10 Home version 1903 machine.

**Comment by Serg-Norseman** [comment]
Thank you very much for the error found!
In the script for the formation of the portable package there was an error due to which the executable file of the program did not get into the archive. In a rush to release preparation, I missed it.

And by the way. The portable version of the package does not imply unpacking to the installation folder of a regular distribution. A portable must be execute from an arbitrary place of unpacking. The current release is made as portable especially in order not to overlap the previous installation.

**Comment by Serg-Norseman** [comment]
The script is fixed, the package is updated.
