### ISSUE TITLE
Children without parents not flagged (enhancement)

### ISSUE THREAD

**Issue by Dreamer451** [Serg-Norseman/GEDKeeper#224]
The "Check Database" tool does not flag the issue when there are children without parents. For example John Smith and Mary Jones have a child Carl Smith. Delete John and Mary and Carl remains a child of non-existent parents.

**Comment by Serg-Norseman** [comment]
This diagnosis should more accurately catch the situation when there is a family record, with one or more children, possibly with events, but in the absence of both parents. That is, FamilyRecord: !IsEmpty() && Husband.Value == null && Wife.Value == null. You also need to select the exact clear message to issue to the user.

**Comment by Serg-Norseman** [comment]
Try to implement it, I will help if necessary. Branch: "feature/family-spouses-check".

**Comment by Dreamer451** [comment]
What number in the `LSID` enum would you like me to use? 789?

**Comment by Serg-Norseman** [comment]
Yes it fits

**Comment by Dreamer451** [comment]
In looking at a previous comment, are you wanting me to address issue 224 ("child found without parents") as well as "Family events found without a family"?

**Comment by Serg-Norseman** [comment]
"Family events found without a family" - it's impossible. I do not understand what you mean.

Personal and family records are substantive database objects. Events - can only be substructures of person or family records. They cannot be on their own without a record that owns them.

And on the main topic of this issue. In your example: if there were two parents, a family and their child. Then you removed the parents. What is remainder? Default: the child’s personal record remains, connected by a link to an empty family record. Do you understand? Family record is not deleted by default, because it is not checked - what if there is not one child, but several. Or there are events, or some other attached data. When you delete parent records, only they are deleted, and the family record remains. Therefore, the diagnosis should clearly catch the situation: family record, with possibly present data of children or events or something else, but without pointers to both spouses. "Record of a family without specified spouses". This is absolutely not the situation when the "child without parents." What is the point? In a normal research database, there are hundreds of such persons without parents. This is normal in the research process. What is the point of displaying all these people in the diagnosis?

**Comment by Dreamer451** [comment]
"Family events found without a family" is impossible--which is why I was confused when that is what I thought you were bringing up. Thankfully you clarified the issue for me in your last paragraph.

I certainly can see where a "child without parents" could have many results, but I had the misconception that this was the issue to be worked. If the spouses had 20 children, then the spouses were deleted, only a single hit for "child without parents" would happen for that family record since fixing one child would fix them all. If this is undesired behavior then I suggest the issue 224 title be changed.

Since you already check to see if the family record is empty, all that is needed for a "Family record without specified spouses" would be a check for husband and wife as null (as you indicated two days ago). The only real issue is the comment to be shown the user (e.g., "Family record detected without specified spouses."). Well, that and whether or not you want to skip or edit that error--and if edit do we just take them to the family edit process (akin to going to the Families tab and double-clicking the 'unknown' family) or would you prefer a dedicated dialog for it?

**Comment by Dreamer451** [comment]
In `CheckFamilyRecord` what I believe should exist is:
`                int chNum = fRec.Children.Count;

                if (husb == null && wife == null)
                    {
                    if (chNum > 0)
                        {
                        CheckObj checkObj = new CheckObj(fRec, CheckDiag.cdChildWithoutParents, CheckSolve.csSkip);
                        checkObj.Comment = LangMan.LS(LSID.LSID_ChildWithoutParents);
                        checksList.Add(checkObj);
                        }
                    else
                        {
                        CheckObj checkObj = new CheckObj(fRec, CheckDiag.cdFamilyRecordWithoutFamily, CheckSolve.csRemove);
                        checkObj.Comment = LangMan.LS(LSID.LSID_FamilyRecordWithoutFamily);
                        checksList.Add(checkObj);
                        }
                    }
                else {
                    if (fRec.IndexOfChild(husb) >= 0) {
                        CheckObj checkObj = new CheckObj(fRec, CheckDiag.cdFatherAsChild, CheckSolve.csRemove);
                        checkObj.Comment = LangMan.LS(LSID.LSID_FatherAsChild);
                        checksList.Add(checkObj);
                        }

                    if (fRec.IndexOfChild(wife) >= 0) {
                        CheckObj checkObj = new CheckObj(fRec, CheckDiag.cdMotherAsChild, CheckSolve.csRemove);
                        checkObj.Comment = LangMan.LS(LSID.LSID_MotherAsChild);
                        checksList.Add(checkObj);
                        }
                    }
`
Does this sound reasonable?

**Comment by Serg-Norseman** [comment]
Speech in these diagnostics is about records of family. Therefore:

1. `ChildWithoutParents` - incorrect wording. Which child? `Family record detected without specified spouses`. It seems the wording has already been specified, but now I see a new one.

2. `FamilyRecordWithoutFamily` - did you decide to do this diagnostics instead of `EmptyFamily` (or renamed what was)? Or, in the example above, you simply did not repeat the code of the previous implementation being saved, leaving it extra? Because it turns out that you are not working on the old implementation, which checked really empty family records without any data at all. This is a very common situation in work bases, where, in addition to family records, without any data (without spouses, without children, without events, without sources and other references), records also remain where spouses or children have been deleted or moved, but some information remains attached.

> Since you already check to see if the family record is empty, all that is needed for a "Family record without specified spouses" would be a check for husband and wife as null (as you indicated two days ago). The only real issue is the comment to be shown the user (e.g., "Family record detected without specified spouses."). Well, that and whether or not you want to skip or edit that error--and if edit do we just take them to the family edit process (akin to going to the Families tab and double-clicking the 'unknown' family) or would you prefer a dedicated dialog for it?

I think that in this case, we need to transfer the user to edit the family record (CheckSolve.csEdit).

> I certainly can see where a "child without parents" could have many results, but I had the misconception that this was the issue to be worked. If the spouses had 20 children, then the spouses were deleted, only a single hit for "child without parents" would happen for that family record since fixing one child would fix them all. If this is undesired behavior then I suggest the issue 224 title be changed.

You're right. But I prefer to break such situations into separate parts. Initially, I did not understand you, I admit. I was only thinking about the diagnosis of absent spouses in the family record. This is a separate situation. And there should be a separate line in the list of diagnostics problems found. In fact, we have to work out the following situations:
1. The family record is completely empty, there is no data at all. Only delete.
2. There are some data in the record (events, or links to notes, or links to sources, or something else), but there are neither children nor spouses. Now - just skip, because there is no decision choosing mechanism (skip, edit, delete).
3. There are children in the record (one or more), but no spouses. Solution options: skip, edit. Because again, there is no selection mechanism (drop-down list), which means either by default skip or edit. Because the fact that it is necessary to process such a line is determined by the checkbox - you can set up editing as the default solution.
4. If there are spouses, then we check only the other conditions already made for searching for user errors (real situations where inattentive users introduce one of the parents as a child, double the child, or create something strange).

From all this it follows that I would prefer to work out separately the situation when in the family record where there are children but no spouses. This view is from the family record. And to work out separately when there is a personal record, it contains a link to the family record of the parents, but in this family record the spouses are not defined - a view from the personal record of child.

You would try to write real code in your branch of your fork. It would be more good. We would discuss specific changes. Because now I occasionally have some doubts and questions to your ideas. But discussion is one thing, and real code is another. Because of this, I keep many of my doubts to myself. In the worst case, I will ask you to revert the changes (remove branch). But we will at least turn out the practice of real code.

At the current stage of our interaction, try not to rename or delete the functionality that was made before you. Like for example, with completely empty families. Because That code is correct and necessary. But I suddenly see a new line for about similar purposes. What is it - renaming? Or a complete replacement of the functional? What for? If we have not discussed this and this is not a bug fix, then you should not change the functionality already done. Because I will reject that. But, fortunately, deleting branch is the safest way to roll back unwanted changes.

**Comment by Dreamer451** [comment]
I would never arbitrarily replace, rename, or edit existing code without prior acceptance.

**Comment by Serg-Norseman** [comment]
Sorry, really. I have interpreted your sample code above incorrectly. Incorrectly appreciated the place where you planned to place it. After your commit, everything fell into place.

**Comment by Serg-Norseman** [comment]
Checked works.
