### ISSUE TITLE
[Feature request] export tree to editable PDF file

### ISSUE THREAD

**Issue by Huaweidev** [Serg-Norseman/GEDKeeper#574]
[Feature request] 
Export tree to editable PDF file to get a high resolution file. Now the exported PDF does not clear when zooming.
![06-15_16-01-02](https://github.com/Serg-Norseman/GEDKeeper/assets/10258421/c2a0ddf0-2657-496a-8276-41ab1b60fe1b)

**Comment by Serg-Norseman** [comment]
Is this screenshot from the PDF? The PDF renderer was vector... I need to double-check everything...

**Comment by Huaweidev** [comment]
> Is this screenshot from the PDF? The PDF renderer was vector... I need to double-check everything...

Yes, Full tree - Print - Microsoft Print to PDF. The PDF is not editable and zoom is not clear.

**Comment by Serg-Norseman** [comment]
At first I didn’t understand what we were talking about.

I have a generation of trees in PDF in the family book and tree album (reduced number of generations). But when you `print' a tree to PDF using `Microsoft Print to PDF`, it simply results in saving a raster wrapped in PDF.

It will take a lot of thought to connect rendering to PDF from reports to save an arbitrary tree. The question is how the user can choose the page size of the virtual PDF canvas, how to scale the tree to fit such a page...

The problem is interesting, but it will be difficult...

**Comment by Huaweidev** [comment]
> At first I didn’t understand what we were talking about.
> 
> I have a generation of trees in PDF in the family book and tree album (reduced number of generations). But when you `print' a tree to PDF using `Microsoft Print to PDF`, it simply results in saving a raster wrapped in PDF.
> 
> It will take a lot of thought to connect rendering to PDF from reports to save an arbitrary tree. The question is how the user can choose the page size of the virtual PDF canvas, how to scale the tree to fit such a page...
> 
> The problem is interesting, but it will be difficult...

No need for users to have too many choices, as long as you can save as a vector PDF to achieve PDF scaling without distortion on the line, just like Microsoft Visio files saved as PDF.
