### ISSUE TITLE
Create the built-in database of national holidays for TipsOfDay

### ISSUE THREAD

**Issue by Serg-Norseman** [Serg-Norseman/GEDKeeper#86]
Create the built-in database (xml/json/yml) of national holidays for TipsOfDay (only for application's languages)

**Comment by Serg-Norseman** [comment]
Question to experts from the field of holywars - which is better to use: xml or json or yaml? I want to make the file editable on fly :)

**Comment by ruslangaripov** [comment]
I'm not a holy war veteran :feelsgood: But I believe if holidays data can be stored within an YAML file, such data **may** be stored as YAML. Otherwise -- since I don't like JSON -- I would use XML with a SAX parser. Being a C++ developer, I think XML SAX will beat YAML parser C++ implementation.

Since the data (information about holidays) is a statical stuff, the choice must be derived from parsing performance. Which depends on parser implementation and how you are using it :smile: You are going to modify the data very rarely, thus, you can ignore editor preferences.

Actually I believe you will see no difference in performance while processing small chunk of data. Therefore, you should select a format that is more comfortable for you as a developer.

**Comment by Serg-Norseman** [comment]
The fundamental possibility is created, then need to improve the mechanism and fill the databases.
